name: Build .NET

on: [push]

jobs:
  build:
    name: Build .NET

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Change directory
      run: cd ./SaSkaDetLata
    - name: Build .NET
      run: dotnet build
